name: 'eslint + fix'
description: 'Lint and fix javascript/typescript code'
author: 'getsentry'
branding:
  icon: 'edit-3'
  color: 'purple'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
