name: "build"
on:
- pull_request
- push
- workflow_dispatch

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup node
    - uses: actions/setup-node@v4
    - name: build
      run: |
        yarn install
        yarn dist

    - name: Use current action
      uses: ./
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
